version: '2'
volumes:
    log: {}

services:
  api:
    container_name: api
    hostname: api
    image: api
    build:
      context: ../services/api
      args:
        PYTHON_COMMONS_HOST: '${PYTHON_COMMONS_HOST}'
        PYTHON_COMMONS_SCHEME: '${PYTHON_COMMONS_SCHEME}'
        PYTHON_COMMONS_PORT: '${PYTHON_COMMONS_PORT}'
    expose:
      - "5000"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
    environment:
      FLASK_SECRET_KEY: '${FLASK_SECRET_KEY}'
      FLASK_LOGIN_SESSION_PROTECTION: 'basic'
      GITHUB_APP_CLIENT_ID: '${GITHUB_APP_CLIENT_ID}'
      GITHUB_APP_CLIENT_SECRET: '${GITHUB_APP_CLIENT_SECRET}'
      PUBLIC_APP_URL: 'http://localhost:3000'
      REDIS_HOST: 'redis'
      RSYSLOG_HOST: 'logserver'
      RSYSLOG_PORT: 514
      DATABASE_HOST: 'database'
      API_URL_PREFIX: '/api/v1'
