version: '2'
volumes:
    sql: {}

services:
  database:
    image: postgres:alpine
    container_name: database
    environment:
      PGDATA: "/var/lib/postgresql/data/rebase"
    volumes:
     - sql:/var/lib/postgresql/data/rebase
