version: '2'
volumes:
    log: {}
    sql: {}

services:
  database:
    image: postgres
    container_name: database
    environment:
      PGDATA: "/var/lib/postgresql/data/rebase"
    volumes:
     - sql:/var/lib/postgresql/data/rebase
