version: '2'

services:
  api:
    volumes:
      - ../services/api:/api
  private_crawler:
    environment:
      LOG_LEVEL: 'DEBUG'
    volumes:
      - ../services/private-crawler/scanner:/pylibs/scanner
  python_parser:
    ports:
      - "25252:25252"
  python_2_parser:
    ports:
      - "25253:25253"
  javascript_parser:
    ports:
      - "7777:7777"
  rq_dashboard:
    extends:
      file: rq-dashboard.yml
      service: rq_dashboard
    ports:
      - "4444:4444"
