version: '2'

services:
  api:
    environment:
      LOG_LEVEL: 'DEBUG'
      CONFIG: '/usr/app/src/conf/gunicorn.dev.conf'
  private_github_scanner:
    environment:
      LOG_LEVEL: 'DEBUG'
  public_github_scanner:
    environment:
      LOG_LEVEL: 'DEBUG'
  population_analyzer:
    environment:
      LOG_LEVEL: 'DEBUG'
  python_parser:
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "25252:25252"
  python_2_parser:
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "25253:25253"
  javascript_parser:
    ports:
      - "7777:7777"
    environment:
      LOG_LEVEL: 'DEBUG'
  rq_dashboard:
    extends:
      file: rq-dashboard.yml
      service: rq_dashboard
  workbench:
    extends:
      file: workbench.yml
      service: workbench
  python_impact:
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "25000:25000"
  javascript_impact:
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "9999:9999"
  database:
    ports:
      - "5432:5432"
