version: '2'

services:
  api:
    volumes:
      - ../services/api:/api
  private_crawler:
    environment:
      LOG_LEVEL: 'DEBUG'
    volumes:
      - ../services/private-crawler/scanner:/pylibs/scanner
  python_parser:
    ports:
      - "25252:25252"
