version: '2'

services:
  api:
    container_name: api
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "5000:5000"
  workbench:
    container_name: workbench
    environment:
      LOG_LEVEL: 'DEBUG'
  private_github_scanner:
    container_name: private_github_scanner
    environment:
      LOG_LEVEL: 'DEBUG'
  public_github_scanner:
    container_name: public_github_scanner
    environment:
      LOG_LEVEL: 'DEBUG'
  population_analyzer:
    container_name: population_analyzer
    environment:
      LOG_LEVEL: 'DEBUG'
  python_parser:
    container_name: python_parser
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "25252:25252"
  python_2_parser:
    container_name: python_2_parser
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "25253:25253"
  javascript_parser:
    container_name: javascript_parser
    ports:
      - "7777:7777"
    environment:
      LOG_LEVEL: 'DEBUG'
  rq_dashboard:
    container_name: rq_dashboard
    extends:
      file: rq-dashboard.yml
      service: rq_dashboard
  workbench:
    container_name: workbench
    extends:
      file: workbench.yml
      service: workbench
  python_impact:
    container_name: python_impact
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "25000:25000"
  javascript_impact:
    container_name: javascript_impact
    environment:
      LOG_LEVEL: 'DEBUG'
    ports:
      - "9999:9999"
  database:
    container_name: database
    ports:
      - "5432:5432"
  proxy:
    container_name: proxy
    environment:
      CONFIG: '/etc/nginx/conf.d/dev.nginx'
    ports:
      - "3000:3000"

