version: '2'

services:
  api:
    volumes:
      - ../services/api:/api
  private_crawler:
    environment:
      LOG_LEVEL: 'INFO'
    volumes:
      - ../services/private-crawler/scanner:/pylibs/scanner
  population_analyzer:
    environment:
      LOG_LEVEL: 'DEBUG'
    volumes:
      - ../services/population-analyzer/leaderboard:/pylibs/leaderboard
  python_parser:
    environment:
      LOG_LEVEL: 'WARNING'
    ports:
      - "25252:25252"
  python_2_parser:
    environment:
      LOG_LEVEL: 'WARNING'
    ports:
      - "25253:25253"
  javascript_parser:
    environment:
      LOG_LEVEL: 'WARNING'
    ports:
      - "7777:7777"
  rq_dashboard:
    extends:
      file: rq-dashboard.yml
      service: rq_dashboard
    ports:
      - "4444:4444"
  python_impact:
    environment:
      LOG_LEVEL: 'WARNING'
    ports:
      - "25000:25000"
  javascript_impact:
    environment:
      LOG_LEVEL: 'WARNING'
    ports:
      - "9999:9999"
  database:
    ports:
      - "5432:5432"
