version: '2'
volumes:
    log: {}

services:
  private_crawler:
    container_name: private_crawler
    hostname: private_crawler
    image: private_crawler
    build:
      context: ../services/private-crawler
      args:
        PYPI_SERVER_SCHEME: '${PYPI_SERVER_SCHEME}'
        PYPI_SERVER_HOST: '${PYPI_SERVER_HOST}'
        PYPI_SERVER_PORT: '${PYPI_SERVER_PORT}'
    environment:
      BREADTH_IMPORTANCE: 4
      GITHUB_CRAWLER_USERNAME: '${GITHUB_CRAWLER_USERNAME}'
      GIHUB_CRAWLER_PASSWORD: '${GITHUB_CRAWLER_PASSWORD}'
      S3_BUCKET: '${S3_KNOWLEDGE_BUCKET}'
      TMPFS_DRIVE_MAX_WRITE: 262144000 # 250M
      TMPFS_DRIVE: '/repos'
      LARGE_DRIVE: '/bigrepos'
      AWS_REGION: '${AWS_REGION}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    tmpfs:
     - /repos:rw,noexec,size=500m
