version: '2'
volumes:
    log: {}

services:
  private_crawler:
    container_name: private_crawler
    hostname: private_crawler
    image: private_crawler
    build:
      context: ../services/private-crawler
      args:
        PYPI_SERVER_HOST: '${PYPI_SERVER_HOST}'
        PYPI_SERVER_SCHEME: '${PYPI_SERVER_SCHEME}'
        PYPI_SERVER_PORT: '${PYPI_SERVER_PORT}'
    environment:
      GITHUB_CRAWLER_USERNAME: '${GITHUB_CRAWLER_USERNAME}'
      GIHUB_CRAWLER_PASSWORD: '${GITHUB_CRAWLER_PASSWORD}'
      S3_KNOWLEDGE_KEYSPACE: 'users/{language}/{module}/'
      S3_KNOWLEDGE_BUCKET: '${S3_KNOWLEDGE_BUCKET}'
      SMALL_REPO_SAFETY_FACTOR: 2
      SMALL_REPO_DIR_SIZE: 524288000 # 500M
      SMALL_REPO_DIR: '/repos'
      LARGE_REPO_DIR: '/big_repos'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    tmpfs:
     - /repos:rw,noexec,size=500m
