version: '2'

services:
  api:
    environment:
      LOG_LEVEL: 'INFO'
      FLASK_LOGIN_SESSION_PROTECTION: 'strong'
    image: '${DOCKER_REGISTRY}/api'
    command: ['/venv/web/bin/gunicorn', '-c', '/usr/app/src/conf/gunicorn.pro.conf', 'rebase.scripts.wsgi:app']
    read_only: true
    tmpfs:
     - /tmp:rw,noexec,size=5m
  private_github_scanner:
    environment:
      LOG_LEVEL: 'INFO'
    image: '${DOCKER_REGISTRY}/private_github_scanner'
    read_only: true
  public_github_scanner:
    environment:
      LOG_LEVEL: 'INFO'
    image: '${DOCKER_REGISTRY}/public_github_scanner'
    read_only: true
  population_analyzer:
    environment:
      LOG_LEVEL: 'INFO'
    image: '${DOCKER_REGISTRY}/population_analyzer'
    read_only: true
  skillgraph:
    image: '${DOCKER_REGISTRY}/skillgraph'
  python_parser:
    environment:
      LOG_LEVEL: 'INFO'
    image: '${DOCKER_REGISTRY}/python_parser'
    read_only: true
  python_2_parser:
    image: '${DOCKER_REGISTRY}/python_2_parser'
    environment:
      LOG_LEVEL: 'INFO'
    read_only: true
  javascript_parser:
    image: '${DOCKER_REGISTRY}/javascript_parser'
    environment:
      LOG_LEVEL: 'INFO'
    read_only: true
  rq_dashboard:
    image: '${DOCKER_REGISTRY}/rq_dashboard'
    ports:
      - "4444:4444"
    read_only: true
  workbench:
    image: '${DOCKER_REGISTRY}/workbench'
    environment:
      LOG_LEVEL: 'INFO'
  python_impact:
    image: '${DOCKER_REGISTRY}/python_impact'
    environment:
      LOG_LEVEL: 'INFO'
    read_only: true
  javascript_impact:
    image: '${DOCKER_REGISTRY}/javascript_impact'
    environment:
      LOG_LEVEL: 'INFO'
    read_only: true
  logserver:
    image: '${DOCKER_REGISTRY}/logserver'
  proxy:
    image: '${DOCKER_REGISTRY}/proxy'
    environment:
      CONFIG: '/etc/nginx/conf.d/root_pro.nginx'
    ports:
      - "80:80"
      - "443:443"
    tmpfs:
     - /nginx_cache:rw,noexec,size=5m
    read_only: true
