version: '2'

services:
  python_2_parser:
    container_name: python_2_parser
    hostname: python_2_parser
    build:
      context: ../services/python-2-parser
      args:
        PYTHON_COMMONS_HOST: '${PYTHON_COMMONS_HOST}'
        PYTHON_COMMONS_SCHEME: '${PYTHON_COMMONS_SCHEME}'
        PYTHON_COMMONS_PORT: '${PYTHON_COMMONS_PORT}'
    image: python_2_parser
    expose:
      - "25253"
